# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c72cacee73fec33a5420541a9be975d783e2eb7a1b0b73a449300eab2870d1ee232284b2c7a3146adae68f2595be8a4801d140a11d90a4376831201ef8a30318

test:
  secret_key_base: 1d8b54b68e38777990658408b536be4bab9f9e42596d50f6e8645f2a1e72b60cb83286ba97758f6f484a425c3cd09c7cb31e179053ae23a726c3fc501e3ec02b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
